CREATE INDEX GDMA2_USERS_INDEX1 ON GDMA2_USERS (FIRST_NAME);

CREATE INDEX GDMA2_USERS_INDEX2 ON GDMA2_USERS (LAST_NAME);

CREATE INDEX GDMA2_ODBC_TYPES_INDEX1 ON GDMA2_ODBC_TYPES (NAME);

ALTER TABLE GDMA2_SERVER_REGISTRATION  ADD UNIQUE ( NAME );

ALTER TABLE GDMA2_SERVER_REGISTRATION ADD CONSTRAINT GDMA2_SERVER_REGISTRATION_FK1 
	FOREIGN KEY (ODBC_TYPE_ID) REFERENCES GDMA2_ODBC_TYPES (ID);

ALTER TABLE GDMA2_TABLE ADD CONSTRAINT GDMA2_TABLE_GDMA2_SERVER__FK1 
	FOREIGN KEY (SERVER_ID) REFERENCES GDMA2_SERVER_REGISTRATION (ID);

CREATE INDEX GDMA2_TABLE_INDEX1 ON GDMA2_TABLE (SERVER_ID);

CREATE INDEX GDMA2_TABLE_INDEX2 ON GDMA2_TABLE (NAME);

ALTER TABLE GDMA2_COLUMN ADD CONSTRAINT GDMA2_COLUMN_GDMA2_TABLE_FK1 
	FOREIGN KEY(TABLE_ID) REFERENCES GDMA2_TABLE (ID);

CREATE INDEX GDMA2_COLUMN_INDEX1 ON GDMA2_COLUMN (TABLE_ID);

CREATE INDEX GDMA2_COLUMN_INDEX2 ON GDMA2_COLUMN (NAME);

CREATE INDEX GDMA2_LOG_INDEX1 ON GDMA2_LOG (LOGGED_AT);

CREATE INDEX GDMA2_LOG_INDEX2 ON GDMA2_LOG (LOGLEVEL);

CREATE INDEX GDMA2_LOG_INDEX3 ON GDMA2_LOG (LOGGERNAME);

ALTER TABLE GDMA2_USER_TABLE_ACCESS ADD CONSTRAINT GDMA2_USER_TABLE_ACCESS_G_FK1 
	FOREIGN KEY (TABLE_ID) REFERENCES GDMA2_TABLE (ID);

ALTER TABLE GDMA2_USER_TABLE_ACCESS ADD CONSTRAINT GDMA2_USER_TABLE_ACCESS_G_FK2 
	FOREIGN KEY (USER_ID) REFERENCES GDMA2_USERS (USER_ID);

CREATE INDEX GDMA2_USER_TABLE_ACCESS_INDEX1 ON GDMA2_USER_TABLE_ACCESS (TABLE_ID);

CREATE INDEX GDMA2_USER_TABLE_ACCESS_INDEX2 ON GDMA2_USER_TABLE_ACCESS (USER_ID);
