CREATE USER GDMA
  IDENTIFIED BY 'GDMA'
  DEFAULT TABLESPACE GDMA
  TEMPORARY TABLESPACE TEMP;

-- USER SQL
ALTER USER GDMA	
	ACCOUNT UNLOCK ;

-- ROLES
ALTER USER GDMA DEFAULT ROLE "RESOURCE","CONNECT";

-- SYSTEM PRIVILEGES

-- QUOTAS
ALTER USER GDMA QUOTA UNLIMITED ON GDMA;
