CREATE OR REPLACE TRIGGER "GDMA"."TRIG_GMDA_AUDIT_HEADER" BEFORE
INSERT ON "GDMA"."GMDA_AUDIT_HEADER" FOR EACH ROW BEGIN
 SELECT NVL(:new.ID, SEQ_GDMA_AUDIT_HEADER.NEXTVAL)
 INTO  :new.ID
 FROM  DUAL;
END;