CREATE OR REPLACE TRIGGER "GDMA"."TRIG_GMDA_SERVER_REGISTRATION" BEFORE
INSERT ON "GDMA"."GDMA_SERVER_REGISTRATION" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW BEGIN
 SELECT NVL(:new.ID, SEQ_GDMA_SERVER_REGISTRATION.NEXTVAL)
 INTO  :new.ID
 FROM  DUAL;
END;
