CREATE OR REPLACE TRIGGER "GDMA"."TRIG_GMDA_AUDIT_RECORD" BEFORE
INSERT ON "GDMA"."GMDA_AUDIT_RECORD" FOR EACH ROW BEGIN
 SELECT NVL(:new.ID, SEQ_GDMA_AUDIT_RECORD.NEXTVAL)
 INTO  :new.ID
 FROM  DUAL;
END;