CREATE OR REPLACE TRIGGER "GDMA"."TRIG_GMDA_ODBC_TYPES" BEFORE
INSERT ON "GDMA"."GDMA_ODBC_TYPES" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW BEGIN
  SELECT SEQ_GDMA_ODBC_TYPES.NEXTVAL
  INTO   :new.ID
  FROM   DUAL;
END;
