CREATE OR REPLACE TRIGGER "GDMA"."TRIG_GMDA_COLUMN" BEFORE
INSERT ON "GDMA"."GMDA_COLUMN" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW BEGIN
	SELECT NVL(:new.ID, SEQ_GDMA_COLUMN.NEXTVAL)
		INTO :new.id
		FROM DUAL;
END;
