/* CREATE SEQUENCES & IDENTITY TRIGGERS*/

DROP SEQUENCE SEQ_GMDA_COLUMN ;
CREATE SEQUENCE SEQ_GMDA_COLUMN ;

CREATE OR REPLACE TRIGGER TRIG_GMDA_COLUMN
BEFORE INSERT ON "GDMA"."GMDA_COLUMN"  
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_COLUMN.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;

DROP SEQUENCE SEQ_GMDA_AUDIT_RECORD ;
CREATE SEQUENCE SEQ_GMDA_AUDIT_RECORD ;
CREATE OR REPLACE TRIGGER TRIG_GMDA_AUDIT_RECORD
BEFORE INSERT ON "GDMA"."GMDA_AUDIT_RECORD"
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_AUDIT_RECORD.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;

DROP SEQUENCE SEQ_GMDA_AUDIT_HEADER ;
CREATE SEQUENCE SEQ_GMDA_AUDIT_HEADER ;
CREATE OR REPLACE TRIGGER TRIG_GMDA_AUDIT_HEADER
BEFORE INSERT ON "GDMA"."GMDA_AUDIT_HEADER"  
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_AUDIT_HEADER.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;

DROP SEQUENCE SEQ_GDMA_TABLE ;
CREATE SEQUENCE SEQ_GDMA_TABLE ;
CREATE OR REPLACE TRIGGER TRIG_GMDA_TABLE
BEFORE INSERT ON "GDMA"."GDMA_TABLE" 
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_TABLE.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;

DROP SEQUENCE SEQ_GDMA_SERVER_REGISTRATION ;
CREATE SEQUENCE SEQ_GDMA_SERVER_REGISTRATION ;
CREATE OR REPLACE TRIGGER TRIG_GMDA_SERVER_REGISTRATION
BEFORE INSERT ON "GDMA"."GDMA_SERVER_REGISTRATION"   
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_SERVER_REGISTRATION.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;

DROP SEQUENCE SEQ_GDMA_ODBC_TYPES ;
CREATE SEQUENCE SEQ_GDMA_ODBC_TYPES ;
CREATE OR REPLACE TRIGGER TRIG_GMDA_ODBC_TYPES
BEFORE INSERT ON "GDMA"."GMDA_ODBC_TYPES"   
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_ODBC_TYPES.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;

DROP SEQUENCE SEQ_DELETE_ME ;
CREATE SEQUENCE SEQ_DELETE_ME ;
CREATE OR REPLACE TRIGGER TRIG_DELETE_ME
BEFORE INSERT ON "GDMA"."DELETE_ME"
FOR EACH ROW
BEGIN
 SELECT NVL(:new."ID",SEQ_GMDA_AUDIT_AUDIT_HEADER.NEXTVAL)
 INTO  :new."ID"
 FROM  DUAL
END;
